// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo.exe -godefs types_windows.go

package devnotify

type (
	_GUID struct {
		Data1 uint32
		Data2 uint16
		Data3 uint16
		Data4 [8]uint8
	}
	_DEV_BROADCAST_HDR struct {
		Size       uint32
		Devicetype uint32
		Reserved   uint32
	}
	_DEV_BROADCAST_DEVICEINTERFACE_W struct {
		Size       uint32
		Devicetype uint32
		Reserved   uint32
		Classguid  _GUID
		Name       [1]uint16
		Pad_cgo_0  [2]byte
	}
)
